### ISSUE TITLE
downloading the dataset

### ISSUE THREAD

**Issue by EvEAskari** [wilbertharriman/tf2-attention-captcha-recognizer#1]
hi, thanks for your for work .
I cant use your dataset, I get the error of permission : "You may need to change the permission to 'Anyone with the link', or have had many accesses "
can you help me, please.

**Comment by wilbertharriman** [comment]
Hi,

Unfortunately, this dataset does not belong to me.
I can only share them with the owner's consent.
Have you tried to look for similar dataset elsewhere?

**Comment by EvEAskari** [comment]
Hi,
Okey then
I'll try to make it work.
Thank you for your help.
